-- Initial schema for ВайбПлан / VibePlan (PostgreSQL 16+).
-- Generated by hand from packages/db/src/schema/*. Покрывает 18 таблиц.

-- === USERS ===
CREATE TABLE IF NOT EXISTS "users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "email" text NOT NULL,
  "name" text,
  "grade" smallint,
  "tz" text NOT NULL DEFAULT 'Europe/Moscow',
  "goal_text" text,
  "anti_burnout" boolean NOT NULL DEFAULT true,
  "energy_today" smallint NOT NULL DEFAULT 7,
  "maya_tone" text NOT NULL DEFAULT 'caring',
  "maya_softness" smallint NOT NULL DEFAULT 95,
  "maya_model" text NOT NULL DEFAULT 'anthropic/claude-3.5-sonnet',
  "theme" text NOT NULL DEFAULT 'matcha',
  "profile_summary" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_unique" ON "users" ("email");

-- === USER_SUBJECTS (ЕГЭ) ===
CREATE TABLE IF NOT EXISTS "user_subjects" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "subject_code" text NOT NULL,
  "target_score" smallint,
  "current_score" smallint,
  "started_at" date,
  "exam_date" date
);
CREATE UNIQUE INDEX IF NOT EXISTS "user_subjects_user_subject_unique" ON "user_subjects" ("user_id", "subject_code");

-- === EGE_MODULES / EGE_TOPICS (ФИПИ) ===
CREATE TABLE IF NOT EXISTS "ege_modules" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "subject_code" text NOT NULL,
  "name" text NOT NULL,
  "sort_order" smallint NOT NULL DEFAULT 0,
  "fipi_year" smallint NOT NULL DEFAULT 2025
);
CREATE INDEX IF NOT EXISTS "ege_modules_subject_idx" ON "ege_modules" ("subject_code", "sort_order");

CREATE TABLE IF NOT EXISTS "ege_topics" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "subject_code" text NOT NULL,
  "module_id" uuid NOT NULL REFERENCES "ege_modules"("id") ON DELETE CASCADE,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "fipi_year" smallint NOT NULL DEFAULT 2025
);
CREATE INDEX IF NOT EXISTS "ege_topics_subject_idx" ON "ege_topics" ("subject_code", "fipi_year");
CREATE INDEX IF NOT EXISTS "ege_topics_module_idx" ON "ege_topics" ("module_id", "code");

-- === EGE_PROGRESS ===
CREATE TABLE IF NOT EXISTS "ege_progress" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "topic_id" uuid NOT NULL REFERENCES "ege_topics"("id") ON DELETE CASCADE,
  "status" text NOT NULL DEFAULT 'new',
  "confidence" smallint NOT NULL DEFAULT 0,
  "last_reviewed" date,
  "solved_count" smallint NOT NULL DEFAULT 0,
  "notes" text,
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "ege_progress_user_topic_unique" ON "ege_progress" ("user_id", "topic_id");
CREATE INDEX IF NOT EXISTS "ege_progress_user_idx" ON "ege_progress" ("user_id");

-- === MOCK_EXAMS (пробники) ===
CREATE TABLE IF NOT EXISTS "mock_exams" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "subject_code" text NOT NULL,
  "date" date NOT NULL,
  "primary_score" smallint,
  "secondary_score" smallint,
  "total_score" smallint NOT NULL,
  "weak_topics" jsonb DEFAULT '[]',
  "notes" text
);

-- === SCHEDULES / LESSONS ===
CREATE TABLE IF NOT EXISTS "schedules" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "source" text NOT NULL DEFAULT 'school',
  "effective_from" date NOT NULL,
  "effective_to" date,
  "raw_ocr" jsonb,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "lessons" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "schedule_id" uuid REFERENCES "schedules"("id") ON DELETE SET NULL,
  "date" date NOT NULL,
  "number" smallint NOT NULL,
  "starts_at" time NOT NULL,
  "ends_at" time NOT NULL,
  "subject_code" text,
  "subject_raw" text NOT NULL,
  "room" text,
  "teacher" text,
  "homework" text,
  "homework_due" date,
  "done" boolean NOT NULL DEFAULT false,
  "voice_notes_url" text
);
CREATE INDEX IF NOT EXISTS "lessons_user_date_idx" ON "lessons" ("user_id", "date");

-- === SESSIONS / POMODOROS ===
CREATE TABLE IF NOT EXISTS "sessions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "date" date NOT NULL,
  "kind" text NOT NULL,
  "starts_at" time NOT NULL,
  "ends_at" time NOT NULL,
  "title" text NOT NULL,
  "subject_code" text,
  "location" text,
  "friend_handle" text,
  "notes" text,
  "status" text NOT NULL DEFAULT 'planned',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "sessions_user_date_idx" ON "sessions" ("user_id", "date");

CREATE TABLE IF NOT EXISTS "pomodoros" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "session_id" uuid NOT NULL REFERENCES "sessions"("id") ON DELETE CASCADE,
  "started_at" timestamptz NOT NULL,
  "ended_at" timestamptz,
  "work_min" smallint NOT NULL DEFAULT 25,
  "rest_min" smallint NOT NULL DEFAULT 5,
  "cycles" smallint NOT NULL DEFAULT 1,
  "completed" boolean NOT NULL DEFAULT false,
  "interruptions" smallint NOT NULL DEFAULT 0
);

-- === HABITS / HABIT_LOGS ===
CREATE TABLE IF NOT EXISTS "habits" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "code" text NOT NULL,
  "title" text NOT NULL,
  "unit" text NOT NULL,
  "target_per_day" smallint NOT NULL DEFAULT 1,
  "target_metadata" jsonb,
  "is_creative" boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "habit_logs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "habit_id" uuid NOT NULL REFERENCES "habits"("id") ON DELETE CASCADE,
  "date" date NOT NULL,
  "value" smallint NOT NULL DEFAULT 0,
  "metadata" jsonb,
  "note" text
);
CREATE UNIQUE INDEX IF NOT EXISTS "habit_logs_user_habit_date_unique" ON "habit_logs" ("user_id", "habit_id", "date");
CREATE INDEX IF NOT EXISTS "habit_logs_user_date_idx" ON "habit_logs" ("user_id", "date");

-- === MEMORY_ANCHORS / DAILY_VIBES / CHAT_MESSAGES ===
CREATE TABLE IF NOT EXISTS "memory_anchors" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "category" text NOT NULL,
  "content" text NOT NULL,
  "source" text NOT NULL DEFAULT 'text',
  "confidence" smallint NOT NULL DEFAULT 100,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "archived_at" timestamptz
);
CREATE INDEX IF NOT EXISTS "memory_anchors_user_idx" ON "memory_anchors" ("user_id", "created_at");

CREATE TABLE IF NOT EXISTS "daily_vibes" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "date" date NOT NULL,
  "quote" text NOT NULL,
  "suggestion" text,
  "energy_pred" smallint,
  "mood" text,
  "generated_by" text NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "daily_vibes_user_date_unique" ON "daily_vibes" ("user_id", "date");

CREATE TABLE IF NOT EXISTS "chat_messages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "role" text NOT NULL,
  "content" text NOT NULL,
  "tokens_in" smallint,
  "tokens_out" smallint,
  "model" text,
  "latency_ms" smallint,
  "context_meta" jsonb,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "chat_messages_user_created_idx" ON "chat_messages" ("user_id", "created_at");

-- === FRIENDS / FOCUS_ROOMS / INTEGRATIONS ===
CREATE TABLE IF NOT EXISTS "friends" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "handle" text NOT NULL,
  "display_name" text,
  "telegram" text,
  "availability" jsonb,
  "tolerance_min" smallint NOT NULL DEFAULT 15,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "focus_rooms" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "host_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "starts_at" timestamptz NOT NULL,
  "ends_at" timestamptz NOT NULL,
  "kind" text NOT NULL DEFAULT 'silent_25_5',
  "participants" jsonb NOT NULL DEFAULT '[]',
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "focus_rooms_host_idx" ON "focus_rooms" ("host_id", "starts_at");

CREATE TABLE IF NOT EXISTS "integrations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "kind" text NOT NULL,
  "external_id" text NOT NULL,
  "external_token" text,
  "meta" jsonb,
  "connected_at" timestamptz NOT NULL DEFAULT now()
);

-- === pgvector extension для эмбеддингов (Phase 6) ===
-- CREATE EXTENSION IF NOT EXISTS vector;
-- ALTER TABLE "memory_anchors" ADD COLUMN IF NOT EXISTS "embedding" vector(1536);
-- CREATE INDEX IF NOT EXISTS "memory_anchors_embedding_idx" ON "memory_anchors" USING ivfflat ("embedding" vector_cosine_ops);